baseURL = 'https://toshioiwai-archive.github.io/'
languageCode = 'en'
title = 'Toshio Iwai Archive'
theme = 'toshioiwai'

[params]
  description = 'Archive of Toshio Iwai'

# Mount opendata directory
[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "../opendata"
  target = "static/opendata"

# Mount opendata as Hugo data source (JSON only)
[[module.mounts]]
  source = "data"
  target = "data"

[[module.mounts]]
  source = "../opendata"
  target = "data/opendata"
  includeFiles = ["*.json"]
